spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Conserva datos entre reinicios
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": false
  sql:
    init:
      mode: never # En producci칩n, no cargar datos autom치ticamente

  # Configuraci칩n para archivos CSV
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# Logging para producci칩n
logging:
  level:
    "[com.josue.pedidos_ms]": INFO
    "[org.hibernate.SQL]": ERROR
